### ISSUE TITLE
When try "webdev serve", then get: "Bad state: Unable to start build daemon."

### ISSUE THREAD

**Issue by alex89607** [janneskoehler/yust_web#1]
Hi! Can you help me to execute your example? When I try to do 'webdev serve' - I get error. Other project(stagehand-simpleFlutterWeb+FirebaseHosting) is worked for me.
I started it like usual:
4 _flutter packages pub global run webdev serve_
3 _firebase init_
2 _pub get_
1 _flutter upgrade_

Tried _'pub run build_runner clean'_ but nothing happened.
________________________________________________________________________________________________
\yust_web-master>flutter packages pub global run webdev serve

[INFO] Building new asset graph completed, took 2.3s
[INFO] Found 1 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you [SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`. The outputs are: lib/models/yust_user.g.dart
Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)
<asynchronous suspension>
#2      connectClient (package:webdev/src/daemon_client.dart:17:23)
#3      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:25:18)
<asynchronous suspension>
#4      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:171:24)
<asynchronous suspension>
#5      ServeCommand.run (package:webdev/src/command/serve_command.dart:138:27)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#7      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     run (package:webdev/src/webdev_command_runner.dart:19:56)
#12     main (file:///C:/Users/briza/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-2.5.0/bin/webdev.dart:17:22)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
pub finished with exit code 255
_____________________________________________________________________________________________________

**Comment by alex89607** [comment]
It seems able to solve with [help](url https://github.com/dart-lang/webdev/issues/211):
_webdev build -- --delete-conflicting-outputs_
